### PR TITLE
Updated studyspace data

### LINKED ISSUE #67: Student Centre Breakdown Doesn't Display

### PR DESCRIPTION
**Pull request by hueyy**
studyspaces.js needs to be periodically updated. it has been updated.

resolves #67

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
Amazing! What I would say though is that 1smlg isn't a student study space (it's a staff building), so we should probably remove that altogether

**Comment by hueyy** [comment]
I agree. We'll need to remove it from the uclapi as well though, so the app
doesn't get conflicting data.

**Comment by ChristopherHammond13** [comment]
@hueyy is a better idea to designate with a boolean on the API whether it's a student study space or not? And then staff who work at 1smlg can still use the API and we can filter out on student integrations

**Comment by hueyy** [comment]
Yeah that makes a lot of sense.

**Comment by ChristopherHammond13** [comment]
Ok I'll merge this PR in for now so that Student Centre is updated.

Another option which I think might be better is to put the filtering logic within the UCL Assistant API? Then that way we can update the available study spaces if there are any issues from the backend and deploy the fix without having to publish a new JavaScript bundle.

**Pull request merged**
