### PR TITLE
Fix non-functional details button on TimetableDetailScreen

### LINKED ISSUE #21: Details button on TimetableDetailScreen does not work
This button does not do anything at the moment.

It should probably open the PersonDetailScreen with the profile of the lecturer / instructor / etc.

However, the data I'm working with is a bit different from that received from the /search/people endpoint:

```
"lecturer": {
    "name": "HIRSCH, Robin (Prof)",
    "department_name": "Computer Science",
    "department_id": "COMPS_ENG",
    "email": "ucacrdh@ucl.ac.uk"
}
```
 There are a few options:

1. We could remove the Details button altogether
2. We could open the PersonDetailScreen anyway and only show the data we have available (i.e. missing status and with a slightly different department name).
3. We could change the Details button to an Email button and open the email client upon press (as with the PersonDetailScreen)

I'm inclined towards Option 3 because this saves the end-user 1 tap. But Option 2 does seem reasonable as well.

### PR DESCRIPTION
**Pull request by hueyy**
Resolves #21 

Implements solution 3, i.e. changes the Details button into a "Send Email" button.

Also made the room name on TimetableDetailScreen clickable => it opens the Rooms search screen and searches for the room in question. It cannot open the RoomDetailScreen directly because roomid is not provided.

[Expo link: https://exp.host/@uclapi/ucl-assistant?release-channel=dev.fix-details_button](https://exp.host/@uclapi/ucl-assistant?release-channel=dev.fix-details_button)

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
If roomid is needed then I can provide that from the API backend

**Comment by hueyy** [comment]
That would be ideal. So just to clarify, this would be a change to the `/timetable/personal` uclapi endpoint so as to include `roomid` and `siteid` in the location attribute of each timetable event. That settles centrally-bookable rooms.

How would the exposing of non-centrally-bookable room data work? One way I can see it happening is if `/roombookings/rooms` supported a `centrally_bookable` boolean query parameter.

Otherwise, a fair bit of location data is already available in the location attribute of each timetable event. I already have the name of the room, the coordinates (sometimes), the capacity, etc and this data is displayed on TimeTableDetailScreen. If booking and equipment data is not available for non-centrally-bookable rooms, then I might just make the room name non-pressable.

**Comment by ChristopherHammond13** [comment]
So the slight issue we have is that we're not technically meant to be making Centrally Bookable rooms available because the purpose of the API was to mimic the room bookings site. but, if you look in my UCL API PR, I'm making lots of room data available for each individual timetable entry so you can probably still render enough information to make the timetable entry useful (e.g. with directions), but equipment etc is probably not relevant for those non-CB rooms.

**Comment by hueyy** [comment]
Okay, I think a reasonable solution would be to make the room name pressable for CB rooms only then. Is there a way I can distinguish between CB rooms & non-CB rooms from the room data available for each timetable entry?

**Comment by ChristopherHammond13** [comment]
@hueyy you'll have a room type code in the JSON response. If you don't have it now, once my PR has been cleaned up for my Timetable API enhancements you'll get the type ID (e.g. CB or DB) so you can check for this and make the app behave accordingly.

**Comment by hueyy** [comment]
Got it. I still need a roomid and siteid in the location attribute of each timetable event before I can navigate to RoomDetailScreen directly.

**Comment by ChristopherHammond13** [comment]
@hueyy just realised that this is still open, whoops! Is this still a relevant PR?

**Comment by hueyy** [comment]
It's still relevant, but let me test it to ensure there are no issues before you merge it.

**Comment by hueyy** [comment]
Merged in fd37848

**Pull request closed without merging**
