### PR TITLE
Fix various issues on TimetableScreen

### PR DESCRIPTION
**Pull request by hueyy**
Resolves Refresh button when displaying Error 500 #592. Now displays the error message at the top of the screen, whilst continuing to display stale timetable data.

Also updates the LastModified component to avoid showing timings in the future, e.g. `Last updated in a few seconds`. This occurs because of a slight time difference between the server time (where lastModified is set) and client time.

Also does not display the timetable is stale message if the timetable is still loading.

[Expo link: https://exp.host/@uclapi/ucl-assistant?release-channel=dev.fix-last_update_time](https://exp.host/@uclapi/ucl-assistant?release-channel=dev.fix-last_update_time)

### CODE REVIEW

**Comment by TuxedoFish** [comment]
Just testing the app out I noticed that if I went on the timetable view and turned airplane mode on then refreshed: it would hide the timetable and you would not see any error. Not too sure why this happened? 

Screenshot_20200312-150419_Expo

**Comment by hueyy** [comment]
This is the QA we need 😂. Will look into this.

**Comment by hueyy** [comment]
@TuxedoFish check it out now?

**Comment by TuxedoFish** [comment]
Sweet all resolved!

**Pull request merged**
