### PR TITLE
Show last-modified header in-app

### LINKED ISSUE #340: Show Last Updated Information
**Is your feature request related to a problem? Please describe.**
Currently it isn't clear to the user the last time the timetable (or study spaces) was updated.

**Describe the solution you'd like**
Use the last modified header to let the user know when the timetable was last updated.

### PR DESCRIPTION
**Pull request by hueyy**
* Shows last-modified header for timetable
  * Shows error if last-modified is more than 30 min ago
* Shows last-modified header on both StudySpaceFavouriteScreen & StudySpaceListScreen
  * Shows error if last-modified is more than 5 min ago

ucl-assistant-api caches timetable data for 5 minutes, and studyspace data for 1 minute.

Resolves #340

[Expo link: https://exp.host/@uclapi/ucl-assistant?release-channel=dev.feature-last_updated_info](https://exp.host/@uclapi/ucl-assistant?release-channel=dev.feature-last_updated_info)

### CODE REVIEW

**Comment by Feverfew** [comment]
I won't approve or block this review, but I would like @TuxedoFish to keep some things in mind when doing this review. @hueyy if possible, please trim the PR here, there seems to be a high amount of unrelated changes here...

Firstly, I've noticed when using the app (before this PR) that there's a short window between when I lost updated the study spaces data and then when UCL Assistant completes its requests for the latest data. This manifests in something like "updated 3 hours ago" quickly changing to "updated a few seconds ago". I'm concerned with this PR that if I open the app once, and then open it more than 6 hours later, I'll see this same big red error briefly, most likely incorrectly. I'd like both of you to make sure that this isn't the case. In particular, if we send a request AND the last-modified header is stale then we show the error. It shouldn't display if we haven't bothered to send a request for more than 6 hours (and it's going to be updated in a second anyway).

Secondly, there should be a differentiation in the error messages between UCL API serving stale data and UCL Assistant not being able to connect to UCL API (or UCL Assistant API). If it fails to connect, but it's still within our "stale window" then we shouldn't really display anything to the user (apart from the last-modified time).

Thirdly, IMO a last-modified header of more than 30 mins for timetable and 5 mins for study spaces is stale. If we were to make this change then my first point must be made sure to be handled!

**Comment by hueyy** [comment]
> Firstly, I've noticed when using the app (before this PR) that there's a short window between when I lost updated the study spaces data and then when UCL Assistant completes its requests for the latest data. This manifests in something like "updated 3 hours ago" quickly changing to "updated a few seconds ago". I'm concerned with this PR that if I open the app once, and then open it more than 6 hours later, I'll see this same big red error briefly, most likely incorrectly. I'd like both of you to make sure that this isn't the case. In particular, if we send a request AND the last-modified header is stale then we show the error. It shouldn't display if we haven't bothered to send a request for more than 6 hours (and it's going to be updated in a second anyway).
> 
> Secondly, there should be a differentiation in the error messages between UCL API serving stale data and UCL Assistant not being able to connect to UCL API (or UCL Assistant API). If it fails to connect, but it's still within our "stale window" then we shouldn't really display anything to the user (apart from the last-modified time).
> 
> Thirdly, IMO a last-modified header of more than 30 mins for timetable and 5 mins for study spaces is stale. If we were to make this change then my first point must be made sure to be handled!

1. is already in place; lastModified date is not shown until the HTTP request is completed (whether successful or unsuccessful)
2. the first is handled by this new error message. the second was already handled before ("error fetching live seating info, etc.")
3. Updated TTLs to 30 min for timetable and 5 min for studyspaces as per suggestion

**Comment by TuxedoFish** [comment]
@hueyy @Feverfew It looks like the FAQ page was updated in this PR as well so I had a few comments on this: 

*

**Comment by TuxedoFish** [comment]
@hueyy @Feverfew On the extra things in the PR it looks like the FAQ page was updated in this PR as well so I had a few comments/suggestions on this:

* The text underneath the question looks misaligned because the corners are rounded I think that text should have some extra padding so it is easier on the eye.

* The card color struck me as weird with the rest of the app, we could we make those cards have the cool gradient.

On the last modified header part. Having looked at the reducer and action it is succinct and good code. On the comment that it might update with an error message if you close and reopen the app after a long time I think to my understanding onRefresh is only called when the page itself is refreshed and not when you close and reopen the page which will then fetch the timetable again. The error message that is displayed is fetched from redux and so this error message only gets updated after the request has finished being made. So to the best of my knowledge I agree with Huey that this should not be an issue. 

* I agree with the time changes for being stale as well!

**Comment by hueyy** [comment]
Good shout with the gradient suggestion. I think it looks much better that way.

**Comment by TuxedoFish** [comment]
Sweet @hueyy ! I am happy to approve, @Feverfew thanks for pointing out those potential issues, I am confident that the code has been written in a way so as to prevent this

**Pull request merged**
